### ISSUE TITLE
Wrong dropout probability

### ISSUE THREAD

**Issue by timmeinhardt** [pmorerio/curriculum-dropout#1]
From my understanding the following line should use the `keep_prob_conv` instead:
https://github.com/pmorerio/curriculum-dropout/blob/5620c5bf8dec55fa9283bfdeb9a337ad37af3609/double_mnist/evaluate_dm.py#L119

Also while the _CNN-2_ is implemented the documentation of the network initialisation seems to refer to the _CNN-1_ (LeNet) with 32 filters:
https://github.com/pmorerio/curriculum-dropout/blob/5620c5bf8dec55fa9283bfdeb9a337ad37af3609/double_mnist/evaluate_dm.py#L93

**Comment by pmorerio** [comment]
Both observations are correct. I will fix it.

**Comment by pmorerio** [comment]
Fixed with the correct probability
https://github.com/pmorerio/curriculum-dropout/blob/2a667c7eecdcf76afba272c59293dfa4f9b5b28c/double_mnist/evaluate_dm.py#L119

Kept the doc very general. In this case `dim_conv1=96` .
https://github.com/pmorerio/curriculum-dropout/blob/2a667c7eecdcf76afba272c59293dfa4f9b5b28c/double_mnist/evaluate_dm.py#L93
