### ISSUE TITLE
Can you explain the data generated methods from train valid test of doubleMnist function ?

### ISSUE THREAD

**Issue by svjack** [pmorerio/curriculum-dropout#2]
the doubleMnist function generate image merge different pics of 0-9 by random indices sampling,
This may be valid for train valid data for the sample sampling indices generator, 
But use independent generator for test data, Not only the pics for add is different with the train / valid 
pics but the indices are not shared (in generated mechanism) , so i can't understand why use this test data
as accuracy measurement, when training, the conclusion for test accuracy always approximate 0.0.

**Comment by pmorerio** [comment]
Hi. The doubleMnist function generates images by superimposing two digits, both taken either from the mnist training or the test set. This is done to avoid mixing mnist training and test sets, otherwise the model could 'see' in test some single digits already seen in training.
Each image will have two digits in it. There are n*(n-1)/2+n = 55 possible combinations (classes), all of which are equally represented in the dateset.
Test accuracy is reported in the paper, and is never 0.0.
Hope this clarifies.
